### ISSUE TITLE
Laravel 5.4 unable to use php-r

### ISSUE THREAD

**Issue by hpiMat** [kachkaev/php-r#38] opened 2018-03-20 12:40 UTC
Hello,
After searching all topics I still wasn't able to use php-r in my project.

I used composer to install 
        "kachkaev/php-r": "^1.0"
Which should take care of creating the namespace for your classes.

When i run the basic example : 

```
use Kachkaev\PHPR\RCore;
use Kachkaev\PHPR\Engine\CommandLineREngine;

 $r = new RCore(new CommandLineREngine('/path/to/R'));
```

Whatever the path, it only points out he doesn't have the Classes landing to the following code
`
PHP Fatal error:  Class 'Kachkaev\PHPR\Engine\CommandLineREngine' not found in eval()'d code on line 1
`
Is there anything i'm missing about the integration?

Sorry for bothering if it is something obvious!

Thank you 
Matthieu

**Comment by kachkaev** [comment] 2018-03-20 12:44
Hi Matthieu,

I haven't used Laravel so I'm not sure what the problem is. Are you using `eval()` in your PHP code is is this done internally by Laravel?

I guess the best place for you to get help from is Laravel's community – hope they have Slack or something similar. I doubt that the issue is to do with `php-r`, because it's `psr-0`-compatible.

Good luck! Give a shout here once you've sorted the thing out!

**Comment by hpiMat** [comment] 2018-03-20 13:03
Ok! i will try to find out how to convert the path to be psr-4 compatible.
I checked and only psr-4 autoload are loaded

**Comment by kachkaev** [comment] 2018-03-20 13:05
We once upgraded this library to psr-4 https://github.com/kachkaev/php-r/pull/24, but then had to revert it https://github.com/kachkaev/php-r/pull/27. Sharing this just to give you some context.

**Comment by hpiMat** [comment] 2018-03-20 14:24
Didn't find the answer I wanted to make it beautiful.
I just added the php script inside my projects and autoloaded them in:
"autoload": {
        "psr-4": {
            "App\\": "app/",
            "Kachkaev\\":"app/Addition/Kachkaev/"
        }
    }
Not the best way since it might not be durable in time.
I don't know where the library is located after being built by composer. 
If i knew that i could improve this fix.

Seems to find the Class now.

**Comment by kachkaev** [comment] 2018-03-20 14:41
Good to know, thank you. I'll close this issue for, but am happy to continue the discussion if anyone wants to contribute a proper fix.

**Closed by kachkaev** 2018-03-20 14:41 UTC

**Comment by samaya6529** [comment] 2018-12-27 01:54
I need to install php-r under the laravel environment.    I've installed the php-r using the command: "composer require kachaev/php-r" and I got the following message:
 


> Using version ^1.0 for kachkaev/php-r
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Nothing to install or update
> Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
> Discovered Package: fideloper/proxy
> Discovered Package: laravel/tinker
> Discovered Package: nesbot/carbon
> Package manifest generated successfully.

However, the Kachkaev Class still could not be found/included using: 

_**use Kachkaev\PHPR\RCore;
use Kachkaev\PHPR\Engine\CommandLineREngine;**_

What step did I miss?
Below is my composer.json file: 

_**{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.0.0",
        "fideloper/proxy": "~3.3",
        "kachkaev/php-r": "^1.0",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "~1.0",
        "phpunit/phpunit": "~6.0",
        "symfony/thanks": "^1.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}**_
