### ISSUE TITLE
php-r stuck at below output

### ISSUE THREAD

**Issue by dipenpatel235** [kachkaev/php-r#39] opened 2018-07-17 09:26 UTC
Output: 
root@localhost> php -f hello-world.php
/root/php-r/hello-world.php:9:
string(8) "./test.R"
/root/php-r/hello-world.php:11:
class Kachkaev\PHPR\RCore#3 (1) {
  private $rEngine =>
  class Kachkaev\PHPR\Engine\CommandLineREngine#2 (1) {
    private $rCommand =>
    string(8) "test.R"
  }
}

after executing it is stuck on above output

below is php code 
`<?php
require "vendor/autoload.php";
use Kachkaev\PHPR\RCore;
use Kachkaev\PHPR\Engine\CommandLineREngine;

$mypath = "test.R";
$r = new RCore(new CommandLineREngine($mypath));
echo var_dump($r);
$result = $r->run(<<\<EOF
x = 1
y = 2
x + y
x + z
x - y
EOF
    );
echo var_dump($result);
echo $result;
?>
`

**Comment by kachkaev** [comment] 2018-07-18 07:05
Hi @dipenpatel235! Does this happen every time or at random?

**Comment by dipenpatel235** [comment] 2018-07-18 07:06
Everytime.

**Comment by kachkaev** [comment] 2018-07-18 07:10
Ah here is the where the issue is coming from I guess:

```php
$mypath = "test.R";
$r = new RCore(new CommandLineREngine($mypath));
```

`$mypath` should point to your R binary rather than some R file. If you are on macos / linux, you should be able to determine this path by typing `which R` in a terminal.

**Comment by dipenpatel235** [comment] 2018-07-18 07:13
R is on
/use/bin/R

**Comment by kachkaev** [comment] 2018-07-18 09:09
So I guess your solution is to use:

```php
$r = new RCore(new CommandLineREngine('/use/bin/R'));
```

I'll close this issue for now, but am happy to continue the discussion my solution does not help.

**Closed** 2018-07-18 09:09 UTC

**Comment by dipenpatel235** [comment] 2018-07-18 09:48
Ohk ..

Got it.
I think in that need to pass R file created by me.

Thanks

**Comment by dipenpatel235** [comment] 2018-07-21 07:08
Hello..
I have done that now but now again issue is like u have asked above.
it is stuck everytime or random ?

Not it is stuck mostly ..only some times it is working..

SO what is solution of that to run everytime ?

Thanks

**Comment by kachkaev** [comment] 2018-07-21 15:38
I'm afraid you are hitting the same error as has been reported in https://github.com/kachkaev/php-r/issues/7. It affects only some people and is likely to do with some low-lever I/O stuff that I don't quite understand. If you know how PHP sends and receivers data when it comes to sub-processes, I'll be glad to consider a PR!
